<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.baeldung.com/springsoap/gen"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             targetNamespace="http://www.baeldung.com/springsoap/gen"
             name="CountryService">

    <types>
        <xsd:schema>
            <xsd:import namespace="http://www.baeldung.com/springsoap/gen" schemaLocation="country.xsd"/>
        </xsd:schema>
    </types>

    <message name="getCountryRequest">
        <part name="parameters" element="tns:getCountryRequest"/>
    </message>

    <message name="getCountryResponse">
        <part name="parameters" element="tns:getCountryResponse"/>
    </message>

    <portType name="CountryServicePortType">
        <operation name="getCountry">
            <input message="tns:getCountryRequest"/>
            <output message="tns:getCountryResponse"/>
        </operation>
    </portType>

    <binding name="CountryServiceSoapBinding" type="tns:CountryServicePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="getCountry">
            <soap:operation soapAction="http://www.baeldung.com/springsoap/gen/getCountry"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="CountryService">
        <port name="CountryServicePort" binding="tns:CountryServiceSoapBinding">
            <soap:address location="http://localhost:9394/ws"/>
        </port>
    </service>

</definitions>